aws-iam-role-cloudfront-poweruser/README.md, aws-iam-role-cloudfront-poweruser/main.tf, aws-iam-role-cloudfront-poweruser/variables.tf, aws-iam-role-ecs-poweruser/README.md, aws-iam-role-ecs-poweruser/main.tf, aws-iam-role-ecs-poweruser/variables.tf, aws-iam-role-infraci/README.md, aws-iam-role-infraci/main.tf, aws-iam-role-infraci/variables.tf, aws-iam-role-readonly/main.tf
=> standardize on source_account_id

aws-acm-cert/README.md, aws-acm-cert/main.tf, aws-acm-cert/module_test.go, aws-acm-cert/outputs.tf, aws-acm-cert/variables.tf
=> move acm cert module

aws-acm-cert/README.md, aws-aurora-mysql/README.md, aws-aurora-postgres/README.md, aws-cloudwatch-log-group/README.md, aws-default-vpc-security/README.md, aws-iam-ecs-task-role/README.md, aws-iam-group-assume-role/README.md, aws-iam-group-console-login/README.md, aws-iam-password-policy/README.md, aws-iam-policy-cwlogs/README.md, aws-iam-role-bless/README.md, aws-iam-role-crossacct/README.md, aws-iam-role-ec2-poweruser/README.md, aws-iam-role-ecs-poweruser/README.md, aws-iam-role-poweruser/README.md, aws-iam-role-readonly/README.md, aws-iam-role-security-audit/README.md, aws-param/README.md, module-template/README.md
Update README examples to v0.14.0 + a few miscellaneous updates.
=> docs update

.travis.yml, Makefile, README.md, aws-single-page-static-site/module_test.go, bless-ca/README.md, bless-ca/ca.tf, bless-ca/iam.tf, bless-ca/kms.tf, bless-ca/lambda.tf, bless-ca/main.tf, bless-ca/module_test.go, bless-ca/outputs.tf, bless-ca/test/main.tf, bless-ca/test/module_test.go, bless-ca/test/variables.tf, bless-ca/variables.tf, testutil/constants.go
Adding a module to configure a [BLESS](https://github.com/Netflix/bless) lambda + kmsauth key
=> Bless module

CHANGELOG.md
Changes accumulating, creating new release. This is the readme update before I tag.
=> release version 0.15.0

.travis.yml, aws-acm-cert/README.md, aws-aurora-mysql/README.md, aws-aurora-postgres/README.md, aws-aurora/README.md, aws-cloudwatch-log-group/README.md, aws-default-vpc-security/README.md, aws-iam-ecs-task-role/README.md, aws-iam-group-assume-role/README.md, aws-iam-group-console-login/README.md, aws-iam-instance-profile/README.md, aws-iam-policy-cwlogs/README.md, aws-iam-role-bless/README.md, aws-iam-role-cloudfront-poweruser/README.md, aws-iam-role-crossacct/README.md, aws-iam-role-ec2-poweruser/README.md, aws-iam-role-ecs-poweruser/README.md, aws-iam-role-infraci/README.md, aws-iam-role-poweruser/README.md, aws-iam-role-readonly/README.md, aws-iam-role-security-audit/README.md, aws-param/README.md, aws-params-reader-policy/README.md, aws-params-secrets-setup/README.md, aws-params-writer/README.md, aws-redis-node/README.md, aws-single-page-static-site/README.md, bless-ca/README.md
This PR upgrades terraform and terraform-docs to more recent versions. terraform-docs has changed output between the versions, so this also updates the readme files.
=> Upgrade terraform and terraform-docs for test

aws-iam-role-poweruser/main.tf, aws-iam-role-route53domains-poweruser/README.md, aws-iam-role-route53domains-poweruser/main.tf, aws-iam-role-route53domains-poweruser/module_test.go, aws-iam-role-route53domains-poweruser/outputs.tf, aws-iam-role-route53domains-poweruser/variables.tf
Adding in a new iam role for route53 poweruser who has all the route53 permissions
cc: @austinylin
=> New route53 poweruser

.gitattributes
https://thoughtbot.com/blog/github-diff-supression
=> Add a .gitattributes to collapsed vendored code during github pull requests

aws-aurora-mysql/README.md
=> Fixed Typo in Readme

aws-iam-role-poweruser/main.tf
add accountalias action for powerusers
=> added action for poweruser accountalias

aws-s3-private-bucket/outputs.tf
=> Fix typo in aws-s3-private-bucket

aws-iam-role-infraci/README.md, aws-iam-role-infraci/main.tf, aws-iam-role-infraci/variables.tf
=> Adding terraform statefile policy to infraci role

aws-cloudwatch-log-group/main.tf, github-webhooks-to-s3/main.tf
Adds Name tags to aws_cloudwatch_logs instances.
=> Add Name tags to cloudwatch logs

aws-aurora/main.tf, aws-iam-group-console-login/main.tf, aws-iam-instance-profile/main.tf, aws-iam-role-infraci/main.tf
=> [fix] ignore_changes also takes the simpler post-0.12 syntax

aws-efs-volume/README.md, aws-efs-volume/main.tf, aws-efs-volume/module_test.go, aws-efs-volume/outputs.tf, aws-efs-volume/variables.tf, bless-ca/test/module_test.go
Support creation of EFS filesystems in cztack
Once this is merged, I'll add an EFS drive to playground and try to get it mounted to some EC2 instances.
=> Support EFS

.travis.yml
* CI
* https://docs.travis-ci.com/user/common-build-problems/#timeouts-installing-dependencies
=> retry downloading dependencies

aws-aurora-mysql/README.md, aws-aurora-postgres/README.md, aws-aurora/README.md, aws-iam-role-crossacct/README.md, aws-iam-role-crossacct/main.tf, aws-iam-role-crossacct/variables.tf, aws-s3-private-bucket/README.md
Augments the aws-iam-role-crossacct for OIDC federation
test in internal repo
=> [feature] Allow the aws-iam-role-crossacct for OIDC federation

aws-nuke.yml
Adding more things to nuke.
* already ran it once
=> nuke cloudwatch log groups

aws-lambda-function/README.md, aws-s3-private-bucket/README.md
I didn't run `make docs` when I added some variables to the modules previously.
=> [fix] run make docs on previous modules

aws-acm-cert/README.md, aws-aurora-mysql/README.md, aws-aurora-postgres/README.md, aws-ecs-service-fargate/README.md, aws-ecs-service/README.md, aws-iam-instance-profile/README.md, aws-iam-role-bless/README.md, aws-iam-role-crossacct/README.md, aws-iam-role-ec2-poweruser/README.md, aws-iam-role-ecs-poweruser/README.md, aws-single-page-static-site/README.md, bless-ca/README.md, github-webhooks-to-s3/README.md
=> upgraded docs to cztack 0.36.0

aws-ecs-service/README.md, aws-lambda-function/README.md, aws-lambda-function/test/main.tf, aws-s3-private-bucket/module_test.go, go.mod, go.sum
Updated the docs (`make docs`), upgraded go-misc (`go get github.com/chanzuckerberg/go-misc` && `make check-mod`), and fixed the aws-lambda-function test.
run `make test TEST="./aws-lambda-function" ` to verify that the new aws-lambda-function is working
=> [fix] upgrade go-misc and update docs

aws-iam-role-bless/README.md, aws-iam-role-cloudfront-poweruser/README.md, aws-iam-role-crossacct/README.md, aws-iam-role-ec2-poweruser/README.md, aws-iam-role-ecs-poweruser/README.md, aws-iam-role-infraci/README.md, aws-iam-role-poweruser/README.md, aws-iam-role-readonly/README.md, aws-iam-role-route53domains-poweruser/README.md, aws-iam-role-security-audit/README.md, snowflake-table-grant-all/README.md, snowflake-table-grant-all/main.tf, snowflake-table-grant-all/variables.tf
Augment the table grant ALL with the ability to issue individual privs to extra roles/shares. 
just terraform init for now
=> [fix] snowflake-table-grant-all: Also allow specifying specific priv grants

scripts/snowflake_generate_grant_all/main.go, snowflake-account-grant-all/README.md, snowflake-account-grant-all/main.tf.json, snowflake-database-grant-all/README.md, snowflake-database-grant-all/main.tf.json, snowflake-integration-grant-all/README.md, snowflake-integration-grant-all/main.tf.json, snowflake-resource-monitor-grant-all/README.md, snowflake-resource-monitor-grant-all/main.tf.json, snowflake-schema-grant-all/README.md, snowflake-schema-grant-all/main.tf.json, snowflake-stage-grant-all/README.md, snowflake-stage-grant-all/main.tf.json, snowflake-table-grant-all/README.md, snowflake-table-grant-all/main.tf.json, snowflake-view-grant-all/README.md, snowflake-view-grant-all/main.tf.json, snowflake-warehouse-grant-all/README.md, snowflake-warehouse-grant-all/main.tf.json
Relaxing the provider version constraints on the generated code. Otherwise was running into an issue where could not find a valid provider when referencing specific versions.
unit/acceptance tests
https://www.terraform.io/docs/configuration/version-constraints.html
=> [fix] Relax Snowflake provider version constraints

.github/workflows/ci.yml, Makefile
I've noticed the linter is failing a lot in this repo, so this is my attempt to fix some of the linting bugs and make it easier to merge PRs from other and dependabot.
=> chore: upgrade tflint

aws-assume-role-policy/module_test.go
Validate that the role trust policy gets updated as expected
N/A
https://czi-tech.atlassian.net/browse/CCIE-679
=> feat: validate that trust policies are created correctly

aws-iam-instance-profile/main.tf
=> feat: Adds SSM agent policy by default to EC2s

aws-iam-instance-profile/main.tf
=> chore: ar/please release retrigger

.github/workflows/release-please.yml
=> feat: update github release to 3.5.0

aws-aurora-postgres/module_test.go, aws-aurora-postgres/outputs.tf, aws-aurora/outputs.tf
=> feat: add db user and pw to outputs

.github/workflows/ci.yml
=> fix: Pin Snowflake version temporarily to 0.53.0

.github/workflows/ci.yml
=> chore: Update checkout action to v3

.github/workflows/ci.yml, Makefile
=> fix: pin snowflake to 0.53.0 pt 2

.github/workflows/ci.yml, aws-s3-public-bucket/main.tf, aws-s3-public-bucket/variables.tf
=> chore: (ONCALL-364) Add logging to aws-s3-public-bucket

.github/workflows/auto-update.yml
=> fix: Upgrade github runner

aws-ssm-params-writer/versions.tf
=> fix: set aws_provider for ssm_writer

aws-iam-policy-dynamodb-rw/README.md, aws-iam-policy-dynamodb-rw/main.tf, aws-iam-policy-dynamodb-rw/variables.tf, aws-iam-policy-dynamodb-rw/versions.tf
=> feat: add dynamodb policy

aws-iam-policy-dynamodb-rw/main.tf
=> fix: sid alphanumeric

aws-s3-public-bucket/main.tf
addresses issue with public access block on public s3 bucket
=> fix: address issue with public access block on public s3 bucket

aws-cloudfront-logs-bucket/main.tf
=> fix: fixing acl issue on cloudfront buckets

aws-s3-private-bucket/variables.tf
=> fix: Add null default as accepted value

aws-s3-private-bucket/variables.tf
Fix variable default to compare with null as separate comparison.
=> fix: default value comparison

aws-ecr-repo/main.tf, aws-ecr-repo/variables.tf, aws-ecr-repo/versions.tf
=> feat: Support image tag mutability and scan settings

databricks-cluster-log-permissions/README.md, databricks-default-cluster-policies/README.md
Update readme's for new modules, and trigger release via commit name
=> fix: CDI-2127 - update readme's and trigger release

Makefile
One more reference to snowflake provider that needs to be tagged
=> fix: Download of snowflake terraform provider

aws-aurora-postgres/outputs.tf
Bubbling this export up to the aurora postgres module
=> feat: Export aws_rds_cluster_instance in aurora postgres module

aws-cloudfront-logs-bucket/main.tf, aws-cloudfront-logs-bucket/variables.tf
Want the option to encrypt bucket via kms
=> feat: Add kms_encryption variable to cloudfront logs bucket

aws-cloudfront-logs-bucket/outputs.tf
Need kms key arn as an output from cloudfront-logs-bucket module
=> feat: Export kms key arn

.github/workflows/ci.yml, aws-aurora-mysql/README.md, aws-aurora-mysql/variables.tf, aws-aurora-postgres/README.md, aws-aurora-postgres/variables.tf, aws-aurora/README.md, aws-aurora/variables.tf
=> feat: Upgrade RDS CAs to rds-ca-ecc384-g1

databricks-s3-volume/main.tf
Dependencies upstream of external location sometimes takes a moment to register
=> fix: CDI-3103 dbx volumes - Add wait for race condition and clean up names

databricks-workspace-e2/main.tf, databricks-workspace-e2/variables.tf
Add option to add a tfe admin service principal to dbx workspaces
=> feat: CDI-3123 Add service principal to workspace module

databricks-workspace-e2/main.tf
=> fix: CDI-3123 Resource block name missing for new dbx admin grant

databricks-workspace-e2/main.tf
=> fix: CDI-3123 dbx service principal ref

.github/workflows/release-please.yml
https://czi-tech.atlassian.net/browse/ONCALL-850
=> chore: replace deprecated fork usage

databricks-catalog-external-location/catalogs.tf
=> fix: CDI-3232 missing dollar sign for text interpolation

aws-aurora-mysql/README.md, aws-aurora-mysql/variables.tf, aws-aurora-postgres/README.md, aws-aurora-postgres/variables.tf, aws-aurora/README.md, aws-aurora/variables.tf
=> fix: update READMEs for aws-aurora, aws-aurora-postgres, aws-aurora-mysql

databricks-cluster-log-permissions/README.md, databricks-cluster-log-permissions/outputs.tf
Trigger release with appropriate commit message
=> feat: trigger release and fix docs

databricks-default-cluster-policies/main.tf
Fix broken dbx policies for small clusters and legacy shared computer
=> fix: CDI-1691 - Resolve small clusters compute policy and legacy shared policy

databricks-s3-volume-existing-catalog/grants.tf
Fix reference to volume name, not bucket name.
=> fix: Conditionally create grant

databricks-s3-volume/grants.tf
Principal reference for catalog grant was erroneous
=> fix: CDI-3446 - Fix volume catalog grant principal

databricks-s3-volume/grants.tf
Current limited permissions for schema aren't really usable and don't really make sense given the name of the variable. Expanding to allow for select permissions
=> chore: Expand dbx volume schema grants

databricks-catalog-external-location/main.tf
Logic cleanup of bucket and IAM role naming in databricks-catalog-external-location.
=> chore: Logic cleanup

release-please-config.json
=> fix: add release-please-config

.github/workflows/auto-update.yml, .github/workflows/ci.yml
=> fix: gh runner deprecated

aws-s3-public-bucket/README.md
manually trigger release please action ([like this other PR](https://github.com/chanzuckerberg/cztack/pull/662)) to pick up the changes made to the aws-s3-public-bucket module and release them in a new version
=> feat: update aws-s3-public-bucket documentation

.github/workflows/ci.yml
This is an AI generated PR.
Execution time: 24632 ms
Cost: $0.08
=> chore: CCIE-4313 replace tibdex/github-app-token

.github/workflows/ci.yml
This is an AI generated PR.
Agent: claude_code
Execution time: 9317 ms
Cost: $0.02
=> chore: CCIE-4332 use GH_ACTIONS_HELPER_*

aps-role/main.tf, aps-role/variables.tf, aps-role/versions.tf
Here is the inspiration for this module: https://medium.com/@KimiHuang/monitor-your-eks-cluster-by-amazon-managed-service-for-prometheus-amp-f009ba149cab
=> feat: Create amp-role module

.github/workflows/terraform-test.yml
This PR is for fixing the IAM role name for terraform test
=> fix: renamed github action role for terraform test
