chanzuckerberg/cztack

README.md, aws-aurora-mysql/README.md, aws-aurora-mysql/main.tf, aws-aurora-mysql/module_test.go, aws-aurora-mysql/outputs.tf, aws-aurora-mysql/variables.tf, aws-aurora-postgres/README.md, aws-aurora-postgres/main.tf, aws-aurora-postgres/module_test.go, aws-aurora-postgres/outputs.tf, aws-aurora-postgres/variables.tf, aws-aurora/README.md, aws-aurora/main.tf, aws-aurora/module_test.go, aws-aurora/outputs.tf, aws-aurora/variables.tf
As part of this move, the modules have been refactored to have a common module. The -mysql and -postgres modules are still useful for setting appropriate defaults for each engine.
Fixes #24 #23
=> move aurora modules

aws-param/README.md, aws-param/variables.tf
aws-param does nothing with the owner variable; it's read only and does no modification of tags. This removes it from the list of variables needed.
=> Remove owner from aws-param

aws-iam-role-readonly/README.md, aws-iam-role-readonly/outputs.tf, aws-param/main.tf
This PR contains 2 separate small fixes:
1) Adds readonly role's ARN as output of the module. Getting the role ARNs is useful in some ECR IAM permission experiments.
2) Fixes the usage of boolean comparison in aws-param, to properly support both bool true and string "true".
=> Output Readonly role ARN, fix bool

aws-params-reader-policy/README.md, aws-params-reader-policy/main.tf, aws-params-reader-policy/outputs.tf, aws-params-reader-policy/variables.tf
This PR moves the params reader policy from being a global policy to direct inline attachment to a role. This is for the special case where multiple different deployments of a service (e.g. cellxgene-rest-api-kidney and cellxgene-rest-api-mouse) both intentionally use the same hard coded service name because they want access to parameters that are common across multiple deployments. In that case, you would do something like <https://github.com/chanzuckerberg/stp-infra/blob/master/terraform/modules/cellxgene-rest-api/main.tf#L60> where the service name is hard coded so that all such services pick up the param path "/stp-staging-cellxgene/*".
However, since the name of the policy matches this path, multiple different deployments will try to create a policy with the same name. This is …
=> [breaking] Turn params reader policy into inline policy to avoid collision

.travis.yml, Makefile, aws-aurora-mysql/README.md, aws-aurora-mysql/main.tf, aws-aurora-mysql/module_test.go, aws-aurora-mysql/variables.tf, aws-aurora-postgres/README.md, aws-aurora-postgres/main.tf, aws-aurora-postgres/module_test.go, aws-aurora-postgres/variables.tf, aws-aurora/README.md, aws-aurora/main.tf, aws-aurora/variables.tf, aws-cloudwatch-log-group/module_test.go, aws-iam-group-console-login/module_test.go, aws-iam-policy-cwlogs/module_test.go, aws-iam-role-bless/module_test.go, aws-iam-role-cloudfront-poweruser/module_test.go, aws-iam-role-crossacct/module_test.go, aws-iam-role-ec2-poweruser/module_test.go, aws-iam-role-ecs-poweruser/module_test.go, aws-iam-role-infraci/module_test.go, aws-iam-role-poweruser/module_test.go, aws-iam-role-readonly/module_test.go, aws-iam-role-security-audit/module_test.go, aws-params-reader-policy/module_test.go, aws-redis-node/module_test.go, testutil/util.go
I set out on this change to write some full `apply` tests for the aurora modules. Along the way I had to made a bunch of small fixes to get things green.
Note that these are the first tests that use our CI VPC. I've decided, for  now, to just bake the relevant IDs into the Makefile in such a way that others an override them.
In theory the aurora tests should run in paralle (`t.Parallel`) but in practice that does not appear to be working and I don't know why.
Fixes #53 and #54
=> Aurora module tests

aws-iam-ecs-task-role/main.tf
Fixes issue mentioned in meta-infra channel. However, cztack should be stable enough for meta's purposes that it can be on v0.14.0 and not master, which would not have pulled this bug in.
=> Bugfix on aws-iam-ecs-task-role policy doc

README.md, aws-iam-instance-profile/README.md, aws-iam-instance-profile/main.tf, aws-iam-instance-profile/module_test.go, aws-iam-instance-profile/outputs.tf, aws-iam-instance-profile/variables.tf
This PR adds a new aws-iam-instance-profile module that creates both an IAM role and an EC2 instance profile. The IAM role has policies attached to allow Systems Manager Agent and Cloudwatch Logs Agent to interact with AWS servers. This also allows us to change the permissions for the EC2 agent in the future if we find other agents or permissions that we want to be opinionated about being the base.
The intent is that we will replace existing AWS roles and instance profiles created in individual modules with the ones created here. This will either require Terraform state migrations or brief downtimes when the roles are recreated. This may also require rotating out existing instances that have different instance profiles from the one created by the original autoscaling group. This may also …
=> Add aws-iam-instance-profile

aws-iam-role-ec2-poweruser/main.tf
This PR bring the aws-iam-role-ec2-poweruser module in line with the other aws-iam-role-* modules by actually using the iam_path variable for the IAM role it generates. This can affect the role's ARN, and all the other modules do set the path based on the user's input (defaulting to '/', so this should be backwards compatible)
=> Add iam_path to ec2 poweruser role

.travis.yml, aws-iam-instance-profile/README.md, aws-iam-instance-profile/main.tf, aws-iam-instance-profile/module_test.go, aws-iam-instance-profile/variables.tf
This PR adds the ability to disable attaching the SSM policy to the role created in aws-iam-instance-profile. It is believed this will disable the ssm-agent, and specifically prevent it from creating the ssm-user on the local machine, which has been messing up some pre-set UIDs.
=> aws-iam-instance-profile Add option to disable attaching SSM policy

aws-iam-ecs-task-role/README.md, aws-iam-ecs-task-role/main.tf, aws-iam-ecs-task-role/variables.tf
This PR adds an optional iam_path argument to aws-iam-ecs-task-role, bringing it in line with our other aws-iam-*-role modules and allowing people to place the role in a specific path.
=> Add iam_path to aws-iam-ecs-task-role

aws-iam-role-readonly/main.tf
Secrets policy was not being attached to the readonly role.
=> Changed policy for readonly to include secrets policy

aws-iam-role-poweruser/main.tf
Deny power users ability to register domains in Route53. 
Next step: create new user to specifically deal with domain registration/transfers in Route53
=> [breaking] Removing ability of powerusers to register domains via route53

aws-iam-role-route53domains-poweruser/README.md, aws-iam-role-route53domains-poweruser/main.tf
Needed to add the route53ReadOnly policy to the Route53 power user IAM role that I created previously. I need to be able to read and download the zone files for our hosted domains and this should give me the privileges to do that.
=> Adding in Route53ReadOnly Access to Route53Domains-PowerUser Role

aws-acm-cert/README.md, aws-acm-cert/main.tf, aws-acm-cert/variables.tf
The new tf provider refuses to overwrite existing route53 records breaking previous functionality. This is a problem for acm since we need the same record for each region. Therefore, we allow route53 records to be overwritten by default.
unittests
https://github.com/terraform-providers/terraform-provider-aws/issues/7918
=> [fix] ACM certificate route53 validation overwrite

Makefile, aws-iam-role-crossacct/main.tf
This enables the role to be recreated without using name_prefix + create_before_destroy.
Also fixes tests for running with go 1.12, will upgrade the travis build later.
* local unit tests
* https://www.terraform.io/docs/providers/aws/r/iam_role.html#force_detach_policies
=> add force_detach_policies to aws_iam_role

.travis.yml, aws-aurora-postgres/module_test.go, aws-aurora-postgres/variables.tf, aws-aurora/main.tf
It seems that we were relying on 9.6 being the default and this broke when 10 become the default.
* travis-ci
*
=>  set engine_version for aws-aurora-postgres

aws-single-page-static-site/outputs.tf
This PR adds the cloudfront hostname and zone ID to the outputs for the single page static site module. This is needed for supporting vanity aliases to a top level domain (e.g cellxgene-example-data.czi.technology) when the actual bucket/cloudfront is not in the same account as the top level domain.
=> Add cloudfront outputs for single-page-static-site

aws-params-reader-policy/README.md, aws-params-reader-policy/main.tf, aws-params-reader-policy/variables.tf
Adds support for the params-reader-policy to support multiple services for the params prefixes it can read. It uses the existing project-env-service pattern, but also allows users to specify other services, as long as those services also share the same project and env, i.e. project-env-service2, project-env-service3.
Instead of instantiating the params reader multiple times and thus adding multiple IAM policy attachment, this allows us to keep it all in a single IAM policy which keeps us from hitting the IAM policy count limit. Should be backwards compatible with existing usage. This is needed for a particular use case where one team is spreading their SSM parameters across multiple names.
=> Support multiple services in params reader policy

aws-s3-private-bucket/main.tf
This PR strengthens the `aws-s3-private-bucket` module by setting 2 more flags `ignore_public_acls` and `restrict_public_buckets` that tell S3 to ignore existing policies that can make a bucket more public than intended.
The 2 previously set flags of `block_public_acls` and `block_public_policy` only prevent setting policies that could open up the bucket, but do not touch or affect the behavior of existing policies that make files/buckets public or available cross-account. This PR tells S3 to ignore the existing policies and block access even when nominally allowed by the existing policies.
I intentionally have not made these overridable for now; if there are use cases where overriding this is desired, we can add that now or in a later PR.
See …
=> aws-s3-private-bucket set ignore_public_acls and restrict_public_buckets

aws-single-page-static-site/README.md, aws-single-page-static-site/main.tf, aws-single-page-static-site/outputs.tf, aws-single-page-static-site/variables.tf
This PR brings features over from CZI's internal repo to the public aws-single-page-static-site module. This includes overriding the bucket name, public access blocks, more allowed headers, ordered cache behavior, more outputs, and upgrading the minimum TLS version.
=> Add internal features to aws-single-page-static-site

aws-ecs-job-fargate/iam.tf, aws-ecs-service-fargate/iam.tf
Fix some permissions that accidentally were made conditional for ECS task execution roles; policy should actually always be attached.
=> Fix aws-ecs-* task execution role permissions

aws-ecs-service/alb.tf
Expects comma separated string, not list.
=> [bugfix] aws-ecs-service fix type of cidr_blocks

aws-acm-cert/README.md, aws-acm-cert/main.tf, aws-acm-cert/variables.tf
Adds the ability for the user to specify the specific order they want for the certificate subject alternative names at a particular time applying. Unfortunately this cannot be a permanent workaround because of <https://github.com/terraform-providers/terraform-provider-aws/issues/8531>, meaning AWS will change the order arbitrarily on their own discretion although the order seems stable within short periods of time allowing the workaround to work. Because of this constantly changing order, just changing the type of cert_subject_alternative_names to a type that allows specifying ordering won't help. This workaround is only needed when the user starts providing more than 1 SAN for a cert.
In most cases, the user can omit this argument, but can possibly set a temporary one time value locally …
=> aws-acm-cert Add workaround for TF bug

aws-ecs-service-fargate/README.md, aws-ecs-service-fargate/outputs.tf, aws-ecs-service/README.md, aws-ecs-service/outputs.tf
To provide the ability to customize the ALB's rules for an ECS service, we need to provide the ARN of the listener so that they can attach aws_lb_listener_rule instances with references to it. This PR outputs the ARN of the HTTPS listener (usually the one you want), and in cases where we do not auto-redirect the HTTP requests to HTTPS, the HTTP listener. (We intentionally do not output the HTTP listener when redirecting to HTTPS, since we'd prefer users not do any custom rules on the HTTP side.)
=> Output ALB listener ARNs from aws-ecs-service

aws-ecs-job-fargate/README.md, aws-ecs-job-fargate/main.tf, aws-ecs-job-fargate/variables.tf, aws-ecs-job/README.md, aws-ecs-job/main.tf, aws-ecs-job/variables.tf, aws-ecs-service-fargate/README.md, aws-ecs-service-fargate/service.tf, aws-ecs-service-fargate/variables.tf, aws-ecs-service/README.md, aws-ecs-service/service.tf, aws-ecs-service/variables.tf
AWS added support for tagging ECS services in a way that is not backwards compatible with ECS services that have been deployed for a long time. Tags can only be added to ECS services that use a new ARN format that embeds a cluster name inside of the ARN, but older ECS service do not have the name embedded.
For some teams, there are many services that are already deployed, and replacing the ECS service just to apply tags will result in user-visible downtime. We provide a flag for users migrating from the CZI internal module to this public cztack module to be able to prevent Terraform from trying to apply tags, in those cases where the user has determined that applying tags is incompatible with the existing resource. It is recommended that at the next possible down time, that the service be …
=> [fix] aws-ecs support not applying tags to services

aws-ecs-job-fargate/iam.tf, aws-ecs-job/iam.tf, aws-ecs-service-fargate/README.md, aws-ecs-service-fargate/iam.tf, aws-ecs-service/README.md, aws-ecs-service/iam.tf, aws-iam-ecs-task-role/main.tf, bless-ca/iam.tf, github-webhooks-to-s3/main.tf
Add tags to IAM roles where project/env/service/owner variables are available. Also updates READMEs for ecs modules to not instantiate own roles, and removes a self reference to the cztack module by URL.
=> Add tags to IAM roles

aws-ecs-service-fargate/iam.tf, aws-ecs-service/iam.tf
Removes permission restriction to only latest version of registry secret; tasks were failing to launch with that restriction even when the secret had only one version and it was marked current.
Also removing kms permission; in most use cases we are currently using the default encryption key and no special permission is needed for it. The permission granted through the current policy is invalid since it isn't actually pointing at a KMS key. Just removing it for now; not adding an input to provide a KMS key ARN for decryption until we actually have that use case.
=> [bugfix] fix permissions on aws-ecs-service secrets

aws-redis-node/main.tf, aws-redis-node/variables.tf
Porting arguments and defaults from CZI internal module library (with the intent of deleting the internal lib module in favor of this one), and upgrading default Redis engine from 5.0.3 to 5.0.5
=> Make aws-redis-node match internal lib, upgrade default

aws-ecs-job-fargate/iam.tf, aws-ecs-job/iam.tf
Forgot to include aws-ecs-job in previous PR #143 for fixing the IAM permissions for reading secrets manager secrets in task execution roles.
=> [fix] fix permissions on aws-ecs-job secrets

aws-iam-role-poweruser/main.tf
Adds iam:UpdateRoleDescription to poweruser, allowing them to update the descriptions of roles. In theory, iam:UpdateRole already has this and more, and the AWS docs say to use iam:UpdateRole, but one team ran into issues where Terraform came back with AWS rejecting their attempts to update the description, saying they lacked permission. Given that Terraform is using the old API, we should give them the permissions here.
=> Add UpdateRoleDescription perms to aws-iam-role-poweruser

aws-aurora-mysql/README.md, aws-aurora-mysql/main.tf, aws-aurora-mysql/variables.tf, aws-aurora-postgres/README.md, aws-aurora-postgres/main.tf, aws-aurora-postgres/variables.tf, aws-aurora/README.md, aws-aurora/main.tf, aws-aurora/variables.tf
Add ability to restrict aws-aurora ingress by security group, not just by CIDR blocks.
=> Allow restricting aws-aurora ingress by security groups

aws-redis-node/README.md, aws-redis-node/main.tf, aws-redis-node/module_test.go, aws-redis-node/variables.tf
aws-redis-node (and its predecessor in shared-infra, redis-node) had a bug (or at least a naming bug), where the variable named "ingress_security_groups" which ostensibly controlled which security groups were allowed to access the cache, instead assigned the security group that were assigned to Elasticache. In all cases in CZI repos so far, this was set to be the security group assigned to the worker nodes, which happened to allow access to all traffic.
The PR makes this module match the description of ingress_security_group by introducing a new security group in between, assigning the cache the new security group and allowing ingress into that security group from the input security groups, only to the port Redis is listening on.
This PR is breaking because we now need the vpc_id as a new …
=> [breaking] Fix aws-redis-node security groups

.travis.yml, Makefile, aws-nuke.yml, scripts/split-build
Note the most elegant solution, but the best quick-win I could find with travis.
* run travis
=> speed up build by paritioning

aws-ecs-service/README.md, aws-ecs-service/alb.tf, aws-ecs-service/variables.tf
- Add the slow_start parameter to the `aws_lb_target_group` resource.
- Not sure how to test this in cztack without applying. Please advise?
- In use, use the slow_start parameter and verify it applies successfully.
- See: https://www.terraform.io/docs/providers/aws/r/lb_target_group.html#timeout
=> Add slow_start parameter to ecs-service-with-alb

aws-nuke.yml
We were running into limits on existing db param groups. I presume this is due to failed runs not cleaning up the resources.
* ran it locally with `aws-nuke -c aws-nuke.yml --profile cztack-ci-1 --no-dry-run`
* https://github.com/rebuy-de/aws-nuke
=> add db param groups to list of things that can be nuked

aws-iam-role-cloudfront-poweruser/README.md, aws-iam-role-cloudfront-poweruser/main.tf, aws-iam-role-cloudfront-poweruser/variables.tf, aws-iam-role-crossacct/README.md, aws-iam-role-crossacct/main.tf, aws-iam-role-crossacct/variables.tf, aws-iam-role-ec2-poweruser/README.md, aws-iam-role-ec2-poweruser/main.tf, aws-iam-role-ec2-poweruser/variables.tf, aws-iam-role-ecs-poweruser/README.md, aws-iam-role-ecs-poweruser/main.tf, aws-iam-role-ecs-poweruser/variables.tf, aws-iam-role-infraci/README.md, aws-iam-role-infraci/main.tf, aws-iam-role-infraci/variables.tf, aws-iam-role-poweruser/README.md, aws-iam-role-poweruser/main.tf, aws-iam-role-poweruser/variables.tf, aws-iam-role-readonly/README.md, aws-iam-role-readonly/main.tf, aws-iam-role-readonly/variables.tf, aws-iam-role-route53domains-poweruser/README.md, aws-iam-role-route53domains-poweruser/main.tf, aws-iam-role-route53domains-poweruser/variables.tf, aws-iam-role-security-audit/README.md, aws-iam-role-security-audit/main.tf, aws-iam-role-security-audit/variables.tf
Allows us to specify an idp arn to roles in this account to allow for SAML Assume role relationships
=> [feature] Adds support for SAML trust relationship to existing roles

Makefile, aws-s3-private-bucket/main.tf, aws-s3-private-bucket/module_test.go, aws-s3-private-bucket/variables.tf
S3 buckets will now have a lifecycle policy that does a few things
1. incomplete multipart uploads will be aborted after 14 days [doc](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html#mpu-abort-incomplete-mpu-lifecycle-config)
2. non-current versions will be moved to infrequent-access storage after 30 days
3. non-current versions will be deleted after 365 days
The test for this module is also changed from just 'init' to doing an apply.
* newly updated unit test
* https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html#mpu-abort-incomplete-mpu-lifecycle-config
=> [feature] lifecycle policy for s3 buckets

aws-iam-role-poweruser/main.tf
Allow poweruser to list users within any account they are poweruser for. This will allow them to view the users within the IAM console. Note that iam:CreateUser and iam:DeleteUser are still explicitly denied in a statement below.
=> [feature]: Allows poweruser role to iam:ListUsers

.travis.yml
The terraform upgrade should fix the build. There is a problem with
terraform versions before 0.12.19 where pulling modules fails.
* travis-ci
* https://status.hashicorp.com/incidents/cgrw595c8kxc
=> [fix] upgrade to terraform 0.12.19 & bless 0.2.10

aws-aurora-mysql/main.tf, aws-aurora-mysql/terraform.tf, aws-aurora-mysql/variables.tf, aws-aurora-postgres/main.tf, aws-aurora-postgres/terraform.tf, aws-aurora-postgres/variables.tf, aws-aurora/main.tf, aws-aurora/terraform.tf, aws-aurora/variables.tf, aws-efs-volume/main.tf
This will allow upgrading aurora database instances to the new certificate authority.
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html
=> [breaking] [feature] allow setting ca_cert_identifier on aurora modules

aws-aurora-mysql/main.tf, aws-aurora-postgres/main.tf, aws-aurora/main.tf, aws-aurora/variables.tf
For Aurora postgres, the parameter group names before Postgres version 10 are named like "aurora-postgresql9.6", but for version 10 and above the name omits the minor version e.g. "aurora-postgresql10". We parse the engine version to distinguish the 2 cases. We also remove the ignore_changes on family, since these parameter group family versions do need to match the engine version.
=> [fix] naming template for Aurora Postgres param group name

aws-aurora/module_test.go, testutil/util.go
Rather than just an init, we run a plan and assert that it did not
error. This should at least catch straightforward semantic errors.
of changes or issues addressed by this PR. Provide links to relevant PRs if any.
* new test!
=> [test] run a plan to test to aws-aurora

aws-aurora/main.tf
Previously if you supplied empty lists for ingress cidr and security
groups you would end up with a diff that terraform could not resolve.
This is presumably because AWS will drop empty ingress rules.
With this change we will only create an ingress if they are configured.
* unit tests
* tested manually in tfe
*
=> [fix] create aurora sg ingress blocks conditionally

aws-s3-private-bucket/README.md, aws-s3-private-bucket/main.tf, aws-s3-private-bucket/variables.tf
This change allows an implementation of `aws-s3-private-bucket` to use the current lifecycle_rule, or provide a different one via a TF variable. For example, in my implementation I'd like to have a shorter 30-day TTL on "current" objects in the bucket. 
This is a little cumbersome, but I'm unsure if there's a cleaner way (new to TF lol) of doing this, since the `s3` resource doesn't take in a named argument but rather a configuration block. 
Verified via `make plan` on a resource. 
=> allow aws-s3-private-bucket take in custom lifecycle_rule

aws-iam-role-crossacct/outputs.tf, aws-params-writer/README.md, aws-ssm-params-writer/README.md, aws-ssm-params/README.md, aws-ssm-params/main.tf, github-webhooks-to-s3/main.tf
* Fixes README files to properly note deprecations; a comment made it into the wrong README file.
* Fixes a README typo.
* Replaces a usage of deprecated aws-param modules with new aws-ssm-params
* Replaces a workaround of a Terraform bug with more straightforward usage now that bug is fixed
* Adds an output to aws-iam-role-crossacct
=> Fix aws-ssm-params readmes, add crossacct output

aws-aurora-mysql/README.md, aws-aurora-mysql/variables.tf, aws-aurora-postgres/variables.tf, aws-aurora/variables.tf
Our defaults are triggering a state where the instance is created and
then immediately rebooted. That reboot races with the destroy operation
leading to errors
[like](https://travis-ci.com/chanzuckerberg/cztack/jobs/292461303).
Setting the default should improve this.
Marked as breaking because it changes the default for these modules.
* CI
=> [breaking] fix tests for aurora

aws-iam-instance-profile/README.md, aws-iam-instance-profile/main.tf, aws-iam-instance-profile/module_test.go, aws-iam-instance-profile/outputs.tf, aws-iam-instance-profile/variables.tf
* Allows passing an existing role to aws-iam-instance-profile, and the module will attach whatever permissions are needed. This allows using roles that are created and managed by other modules (e.g. EKS worker role), but provides ability to attach a standard set of permissions to that role. It will still always create the instance profile, even if the profile will be unused.
* Removes unused permissions from the aws-iam-instance-profile module for using SSM.
Already in use in CZI internal playground deployment.
=> [breaking] [feature] aws-iam-instance-profile reuse existing role and remove SSM support

aws-iam-role-bless/README.md, aws-iam-role-bless/main.tf, aws-iam-role-bless/variables.tf, aws-iam-role-cloudfront-poweruser/README.md, aws-iam-role-cloudfront-poweruser/main.tf, aws-iam-role-cloudfront-poweruser/variables.tf, aws-iam-role-crossacct/README.md, aws-iam-role-crossacct/main.tf, aws-iam-role-crossacct/variables.tf, aws-iam-role-ec2-poweruser/README.md, aws-iam-role-ec2-poweruser/main.tf, aws-iam-role-ec2-poweruser/variables.tf, aws-iam-role-ecs-poweruser/README.md, aws-iam-role-ecs-poweruser/main.tf, aws-iam-role-ecs-poweruser/variables.tf, aws-iam-role-infraci/README.md, aws-iam-role-infraci/main.tf, aws-iam-role-infraci/variables.tf, aws-iam-role-poweruser/README.md, aws-iam-role-poweruser/main.tf, aws-iam-role-poweruser/variables.tf, aws-iam-role-readonly/README.md, aws-iam-role-readonly/main.tf, aws-iam-role-readonly/variables.tf, aws-iam-role-route53domains-poweruser/README.md, aws-iam-role-route53domains-poweruser/main.tf, aws-iam-role-route53domains-poweruser/variables.tf, aws-iam-role-security-audit/README.md, aws-iam-role-security-audit/main.tf, aws-iam-role-security-audit/variables.tf
Adds a source_account_ids field to aws-iam-role-* modules, which will allow multiple accounts' root to assume role, assuming the user/role in the other accounts allow the role assumption.
Either source_account_id or source_account_ids or both work; the intent is to keep backwards compatibility for now, but potentially eliminate source_account_id. Officially document that source_account_id is deprecated.
=> [feature] aws-iam-role-*: Allow multiple accounts to assume role, deprecate source_account_id

aws-aurora-mysql/README.md, aws-aurora-mysql/main.tf, aws-aurora-mysql/outputs.tf, aws-aurora-mysql/variables.tf, aws-aurora/README.md, aws-aurora/outputs.tf
- Exposing the aurora cluster endpoint so that we can attach a different class of instance to the cluster.
- Exposing the `db_parameter_group_name` which is also required when externally creating a new instance.
- Fix a bug where the module was passing the `engine_version` was being passed as the `params_engine_version` as well. This works when they're both `5.7` or some other select values but not always. For example, if version is `5.7.28` or any other minor version, that would be considered an invalid `params_engine_version` value.
Tested this code directly by pulling this module into my existing source.
=> Expose the cluster endpoint in the aurora module

aws-iam-group-assume-role/main.tf, aws-iam-role-crossacct/main.tf
I'm working with GitHub Actions - its canonical AWS credentials action requires that 'sts:TagSession' permissions be granted for role assumption:
https://github.com/aws-actions/configure-aws-credentials#permissions-for-assuming-a-role
I'm not sure if we have a policy reason for denying this permission (if so, I can look into alternative auth methods) but it seemed like a minor behavior change.
This change enables a pretty straighforward ECR build&push pipeline via GHA: https://github.com/chanzuckerberg/tfe-docker/blob/actiontest/.github/workflows/daily-rebuild.yml
=> Include TagSession privilege for assumed roles.

aws-iam-role-poweruser/README.md, aws-iam-role-poweruser/main.tf, aws-iam-role-poweruser/variables.tf
We optionally enable the poweruser role for sts:AssumeRoleWithWebIdentity. 
Follows convention of the cross-act role.
=> [feature] AWS Poweruser role allows OIDC sts:AssumeRoleWithWebIdentity

aws-iam-role-readonly/README.md, aws-iam-role-readonly/main.tf, aws-iam-role-readonly/variables.tf
Authorize the readonly role for OIDC federation. Optionally limit kms read permissions.
=> [feature] Readonly role OIDC federation enabled + kms decrypt optional

aws-iam-role-poweruser/README.md, aws-iam-role-poweruser/main.tf, aws-iam-role-poweruser/variables.tf
Occasionally we might want to disable the extra iam actions in poweruser role, make it configurable.
=> [feature] Optionally disable poweruser role iam actions

aws-iam-role-poweruser/main.tf
We're depending on a resource with a count, we need to reflect the index in the dependency as well.
=> [fix] Use index when referring to a dependency with a count

aws-acm-cert/README.md, aws-iam-role-crossacct/README.md, aws-iam-role-crossacct/main.tf, aws-iam-role-crossacct/module_test.go, aws-iam-role-crossacct/variables.tf
Want to give us the ability to tag this IAM role.
unittests
https://github.com/chanzuckerberg/aws-oidc/pull/26
=> [feature] aws-iam-role-crossacct: Allow tagging

aws-aurora-mysql/README.md, aws-aurora-mysql/main.tf, aws-aurora-mysql/variables.tf, aws-aurora-postgres/README.md, aws-aurora-postgres/main.tf, aws-aurora-postgres/variables.tf, aws-aurora/README.md, aws-aurora/main.tf, aws-aurora/variables.tf
Enable setting auto_minor_version_upgrade on aurora databases.
We have been relying on the default of `true`. This allows you to disable it.
* CI
* https://www.terraform.io/docs/providers/aws/r/rds_cluster_instance.html#auto_minor_version_upgrade
=> [feature] support auto_minor_version_upgrade

aws-lambda-function/main.tf, aws-lambda-function/module_test.go, aws-lambda-function/test/main.tf, aws-lambda-function/variables.tf
Enable setting log retention parameter for the cloud watch log groups
attached to lambdas.
* CI
=> [feature] setting lambda cloudwatch log retention

README.md, aws-acm-cert/module_test.go, aws-aurora-mysql/module_test.go, aws-aurora-postgres/module_test.go, aws-aurora/module_test.go, aws-cloudfront-logs-bucket/module_test.go, aws-cloudwatch-log-group/module_test.go, aws-default-vpc-security/module_test.go, aws-efs-volume/module_test.go, aws-iam-group-console-login/module_test.go, aws-iam-instance-profile/module_test.go, aws-iam-role-bless/module_test.go, aws-iam-role-cloudfront-poweruser/module_test.go, aws-iam-role-crossacct/module_test.go, aws-iam-role-ec2-poweruser/module_test.go, aws-iam-role-ecs-poweruser/module_test.go, aws-iam-role-infraci/module_test.go, aws-iam-role-poweruser/module_test.go, aws-iam-role-readonly/module_test.go, aws-iam-role-route53domains-poweruser/module_test.go, aws-iam-role-security-audit/module_test.go, aws-iam-secrets-reader-policy/module_test.go, aws-lambda-function/module_test.go, aws-redis-node/module_test.go, aws-s3-private-bucket/module_test.go, bless-ca/test/module_test.go, module-template/module_test.go, testutil/test.go
Rename to make the purpose of this test stage more clear - it is for
setting up test context. It still returns a terraform.Options (for use
in applying and validating code).
After some use, 'options' just felt like the wrong name.
* CI
=> rename test.Options to test.Setup

aws-s3-private-bucket/README.md, aws-s3-private-bucket/main.tf, aws-s3-private-bucket/variables.tf
**Motivation:** 
I was importing an s3 bucket into Terraform ([PR](**https://github.com/FB-PLP/terraform-infra-management/pull/543**)) and found that they have a grant in which the type is `Group` there, so I updated this module to support the `Group` type in the grant. 
**Changes in this PR:** 
1. make the user be able to specify either `uri` or `canonical_user_id` with exclusive or relationship, if not exclusive or, then we treat them as invalid inputs
2. if specifying `uri`, then the grant type is `Group`, otherwise, the grant type is `CanonicalUser`
1. Testing in [PR](**https://github.com/FB-PLP/terraform-infra-management/pull/543**), and importing the bucket worked
2. If we specify both `uri` or `canonical_user_id`, it doesn't create the grant, in this case, the user will then follow …
=> [feature] make the type for the grant in s3  bucket as configurable

.github/workflows/ci.yml, Makefile, aws-cloudwatch-log-group/README.md, aws-cloudwatch-log-group/main.tf, aws-cloudwatch-log-group/variables.tf
This PR adds the `retention_in_days` parameter to `aws-cloudwatch-log-group` module. 
Ran `make plan` against project project importing this module
=> [feature] configure cloudwatch-log-group retention policy

aws-s3-private-bucket/main.tf, aws-s3-private-bucket/variables.tf
Tested in LP's terraform repo (PR 553)
=> [fix] s3 bucket abort_incomplete_multipart_upload_days should be read from lifecycle

aws-iam-role-poweruser/main.tf
Motivation: 
I am working on removing a number of unused IAM policies in the summitps AWS account.  It would be cool to have the permissions to use the access advisor to see how and when those policies were used. (also suggested by this [article](https://aws.amazon.com/blogs/security/remove-unnecessary-permissions-in-your-iam-policies-by-using-service-last-accessed-data/)). poweruser currently doesn’t have the `iam:GetServiceLastAccessedDetails` permissions (together with iam:generate-service-last-accessed-details, and both are for read permissions). 
See the thread link in slack in LP's terraform repo PR 573. (not linking here as it will be public) 
See LP's terraform repo PR 573.
=> [feature] add access advisor permissions to poweruser

aws-iam-role-poweruser/main.tf
This will enable to poweruser to see the details of the IAM user and their inline policy. 
We already have the ability for `iam:GetRole` and `iam:GetRolePolicy`, so I think the permissions for IAM user should be grated similarly. 
(This will also facilitate LP in importing some IAM users into TF.)
To be tested in LP's repo.
=> [feature] Grant poweruser the permissions to view IAM user details

aws-lambda-function/README.md, aws-lambda-function/main.tf, aws-lambda-function/outputs.tf, aws-lambda-function/variables.tf
I want to use this module to create lambdas for cloudfront. That
requires supporting lambda@Edge. The two main changes here are:
1. Adding edgelambda as an authorized service for the role
2. granting permission create/update permission on * log groups.
The second is I suppose slightly controversial. because its an edge
lambda, we would have to precreate the log groups in every single aws
region, and I have no clue how to do that. I think this is an okay
tradeoff for now, and tried to document that in the description.
Test Plan:
wait for CI
use it in stacked TF and see if it works.
=> Allow lambda@edge in aws-lambda-function module

aws-lambda-edge-add-security-headers/main.tf
This was using the wrong hash function for the lambda source_code_hash.
THis means that every plan suggested a change, but no change actually
happened. The only problem was that the hash function was different, so
the comparison always had a difference.
Test Plan: plan is clean when using this ref
=> [fix] aws-lambda-edge-security-headers: permanently dirty plan

aws-iam-role-bless/main.tf, aws-iam-role-bless/module_test.go, aws-iam-role-bless/variables.tf, aws-iam-role-cloudfront-poweruser/main.tf, aws-iam-role-cloudfront-poweruser/module_test.go, aws-iam-role-cloudfront-poweruser/variables.tf, aws-iam-role-crossacct/main.tf, aws-iam-role-crossacct/module_test.go, aws-iam-role-crossacct/variables.tf, aws-iam-role-ecs-poweruser/main.tf, aws-iam-role-ecs-poweruser/module_test.go, aws-iam-role-ecs-poweruser/variables.tf, aws-iam-role-infraci/main.tf, aws-iam-role-infraci/module_test.go, aws-iam-role-infraci/variables.tf, aws-iam-role-poweruser/main.tf, aws-iam-role-poweruser/module_test.go, aws-iam-role-poweruser/variables.tf, aws-iam-role-readonly/main.tf, aws-iam-role-readonly/module_test.go, aws-iam-role-readonly/variables.tf, aws-iam-role-route53domains-poweruser/main.tf, aws-iam-role-route53domains-poweruser/module_test.go, aws-iam-role-route53domains-poweruser/variables.tf, aws-iam-role-security-audit/main.tf, aws-iam-role-security-audit/module_test.go, aws-iam-role-security-audit/variables.tf
My previous PR was failing because https://github.com/chanzuckerberg/cztack/commit/209f50326c28c9fd05d1a5b5e1a6ac6acdead1fd brought in https://github.com/chanzuckerberg/go-misc/commit/d32d5af6473ec4b5f4e0ad01fea82066a5ff149f which enforces the env/owner/service/project tagging scheme over a `tags` variable. This fixes it for the other modules (it seems the test suite is only configured to run certain module tests when there are changes to those modules), which is why this didn't get picked up earlier. 
I don't have permissions to run the full test suite, but `make test-ci TEST=./MODULE` seems to make it past the initial Terraform static checks. Let's see if CI tests fully pass. 
=> add tags specified by tftest

.github/workflows/ci.yml, aws-cloudwatch-log-retention-manager/README.md, aws-cloudwatch-log-retention-manager/main.tf, aws-cloudwatch-log-retention-manager/module_test.go, aws-cloudwatch-log-retention-manager/terraform.tf, aws-cloudwatch-log-retention-manager/variables.tf
Create a scheduled lambda function to iterate through all Cloudwatch Log
Groups and enforce a maximum retention. This is particularly useful for
deletion efforts on the Education team, because Lambda@Edge functions
(amongst others) can log PII, but have no way to control retention via
Terraform.
It's a good question whether we want this to be:
- Opt-out: Applies to all log groups unless specified otherwise.
- Opt-in: Only applies to specific prefixes.
I think there's probably not much downside in the opt-out approach. It's
the safest in terms of deletion requirements, and its rare for us to have logs
that we would consider "permanent", since any of them could potentially
contain PII.
Test Plan: Dry runs in the console with the `put_retention_policy`
commented out.
=> aws-cloudwatch-logs-retention-manager

.github/CODEOWNERS
As part of our efforts to improve testing and consistency across the
cztack modules, code owners is going to be restricted to a smaller
group.
=> restrict codeowners

scripts/snowflake_generate_grant_all/main.go, snowflake-account-grant-all/main.tf.json, snowflake-database-grant-all/main.tf.json, snowflake-integration-grant-all/main.tf.json, snowflake-resource-monitor-grant-all/main.tf.json, snowflake-schema-grant-all/main.tf.json, snowflake-stage-grant-all/main.tf.json, snowflake-table-grant-all/main.tf.json, snowflake-view-grant-all/main.tf.json, snowflake-warehouse-grant-all/main.tf.json
Moving the Snowflake grant ALL modules to TF 0.13 syntax.
See "Use Provider" at the top right of https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest
=> Upgrade Snowflake modules to TF 0.13

aws-cloudwatch-log-retention-manager/main.tf
Oops, I forgot to change the rate back to a reasonable timer after
testing. This definitely doesn't need to run every 5 minutes, even every
12 hours is probably too much, but I'd rather it run frequently so we
might find the failures sooner too.
Test Plan: inspection
=> Run log retention lambda every 12 hours.

aws-cloudwatch-log-retention-manager/main.tf
Another typo. This has not been my best work.
Test Plan:
put up PR
use commit hash as ref to apply module in terraform
manually run lambda from aws console
see that there are no syntax or runtime errors
=> Fix typo in aws-cloudwatch-log-retention-manager

aws-iam-role/README.md, aws-iam-role/main.tf, aws-iam-role/variables.tf
This adds a dynamic statement to the `aws_iam_role` module's `assume_role_policy`, allowing the role to `sts:AssumeRoleWithSAML`. 
This is used in https://github.com/FB-PLP/terraform-infra-management/pull/900 (its TF plan can be found [here](https://si.prod.tfe.czi.technology/app/lp-infra/accounts-summitps/runs/run-CT4Efqe37bAXbNK5))
=> Update assume_role_policy in aws_iam_role

aws-iam-role/README.md, aws-iam-role/main.tf, aws-iam-role/variables.tf
This is a resubmission of https://github.com/chanzuckerberg/cztack/pull/274. I tried to incorporate some feedback about making it backwards compatible, but that didn't work. I didn't notice that my TF plan completed unsuccessfully, hence me merging a bit too early. This PR reverts that and submits the change as we discussed. 
Sorry for the extra review request! 
In situations where you were appending new resources to attached_policies_arns that didn't exist yet, Terraform would throw the following error:
```
Error: Invalid for_each argument
on .terraform/modules/aws-role-devserver-restart/aws-iam-role/main.tf line 41, in resource "aws_iam_role_policy_attachment" "policy_attachment":
41:   for_each   = toset(var.attached_policies_arns)
The "for_each" value depends on resource attributes …
```
=> [breaking] Replace attached_policies_arns in aws_iam_role with map

.github/workflows/ci.yml, aws-redis-replication-group/README.md, aws-redis-replication-group/main.tf, aws-redis-replication-group/module_test.go, aws-redis-replication-group/outputs.tf, aws-redis-replication-group/terraform.tf, aws-redis-replication-group/variables.tf
This module is similar to [aws-redis-node](https://github.com/chanzuckerberg/cztack/tree/main/aws-redis-node), however it creates a Elasticache Redis cluster using a replication group.
The motivation to create this module is because encryption options (in-transit and at rest) are only available when you create your cluster using a replication group.
- Manual tests (already applied to IDseq)
- Unit tests
=> [feature] Add aws-redis-replication-group

aws-s3-public-bucket/main.tf, aws-s3-public-bucket/variables.tf
Adds functionality from CZI's private version of this module.
* Add ability to disable versioning by default on public S3 buckets.
Leaves default behavior of enabling versioning intact
* Optionally require TLS for every get object. Default to true.
=> [feature] aws-s3-public-bucket require https, allow disabling versioning

aws-aurora-postgres/main.tf, aws-redis-replication-group/README.md, aws-s3-public-bucket/README.md
Enable logs for aurora postgresql
=> enable clouldwatch log exports for aurora postgresql

aws-s3-private-bucket/README.md, aws-s3-private-bucket/terraform.tf
Adding more flexibility to provider versions for s3 private bucket module. https://aws.amazon.com/fr/about-aws/whats-new/2021/02/amazon-s3-now-supports-aws-privatelink/ caused a breaking change in https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/571 which triggered an upgrade to aws provider 3.X as the only viable upgrade path.
I am not sure >=2.60.0 is the "right" choice here but it seemed "reasonable enough"
=> [fix] s3-private-bucket more lenient aws provider version

aws-redis-node/README.md, aws-redis-node/main.tf, aws-redis-node/variables.tf
Allows CIDR-based security group to Redis, in addition to source based security groups. The new variable is marked as optional, so this shouldn't be a breaking PR.
The current unit test for this module doesn't seem to test anything (the Validate step is empty?), but I am happy to expand it. I might need some guidance though.
=> [feature] Add CIDR blocks based security group to Redis

aws-lambda-function/README.md, aws-lambda-function/main.tf, aws-lambda-function/outputs.tf, aws-lambda-function/variables.tf
Allow lambdas to configure vpc_config and memory_size
=> [feature]: lambda vpc_config and memory_size

aws-s3-private-bucket/main.tf, aws-s3-private-bucket/variables.tf
Add support for logging S3 access to another bucket or prefix to the private bucket module.
I generated a tf file that created two buckets (a content bucket, and a logging bucket) and set the logging config of one bucket to refer to the other. The logging config in the plan had logging enabled for the content bucket and disabled for the logging bucket.
Tests pass.
=> Initial updates for supporting s3 bucket logging targets.

aws-s3-account-public-access-block/main.tf, aws-s3-private-bucket/main.tf, aws-s3-private-bucket/variables.tf
Adds support for passing in a canned acl variable. Defaults to "private"
for backwards compatibility. Canned acl variable is ignored if grants
argument is passed.
While here, fix lint issues and typos.
=> [feature] aws-s3-private-bucket add canned acl variable

.github/workflows/auto-update.yml
Adds auto-updating of PR branches with the content of the base branch, if the PR branch is marked for auto-merge in Github.
I have examined the Typescript code in https://github.com/tibdex/auto-update/blob/main/src/index.ts for security but have not examined the Javascript that it compiles into, and I have also examined the Github Action that they use to release new Github Actions versions. This PR specifically locks the branch to tag v2.1.2 rather than v2; the underlying release process reassigns the vX and vX.Y tag on minor and patch releases, and this hopefully minimizes (although does not eliminate) the possibility of malicious code being introduce into the action.
Note that we have set up the action to only trigger on pushes to `main` branch; if a PR has a base branch that is not …
=> Auto merge main branch on update for branches with auto-merge enabled

.github/workflows/ci.yml, aws-default-vpc-security/module_test.go, aws-iam-group-console-login/module_test.go, aws-iam-instance-profile/module_test.go, aws-iam-policy-cwlogs/module_test.go, aws-iam-secrets-reader-policy/module_test.go, aws-iam-secrets-reader-policy/test/main.tf, aws-params-reader-policy/module_test.go, aws-s3-account-public-access-block/module_test.go, aws-single-page-static-site/module_test.go, aws-sns-lambda/module_test.go
* Fixes an issue where running the aws cli (specifically aws sts get-caller-identity) would exit with error 255, and fail the build. It turns out that since we use ubuntu-latest (which recently upgraded to ubuntu 20.04 with aws cli v2) we were running into <https://github.com/aws/aws-cli/issues/5262>. When run on a machine that is running on Azure cloud (as Github Actions does), since the Azure metadata service runs on the same 169.254.169.254 location that AWS metadata service does. We disable using the metadata service by globally setting AWS_EC2_METADATA_DISABLED environment variable.
* Instead of having enumerate every single module and have to remember to change .github/workflows/ci.yml to add new modules/remove deprecated modules, we use a feature added by Github Actions in April …
=> Fix running aws cli on GH Actions/Azure, get modules dynamically

aws-aurora-postgres/README.md, aws-aurora-postgres/variables.tf
This disables auto version upgrades by default, since several teams have run into trouble by setting a specific engine version, having AWS upgrade their DB's behind the scenes, and then having TF try (and fail) to downgrade their DB's, causing downtime. It also adds some docs on how to use these parameters more safely.
=> [breaking] aws-aurora-postgres: Disable auto minor version upgrade by default.

aws-acm-cert/main.tf, aws-aurora/main.tf, aws-default-vpc-security/main.tf, aws-iam-policy-cwlogs/main.tf, aws-params-reader-policy/main.tf, aws-single-page-static-site/main.tf, bless-ca/iam.tf, bless-ca/kms.tf, bless-ca/test/main.tf, github-webhooks-to-s3/firehose.tf, github-webhooks-to-s3/main.tf
As modules in this repository are intended for use with Terraform 0.12 or later, it's safe to remove remaining instances of deprecated interpolation-only strings of the form `"${foo}"`. This should reduce the noise from deprecation warnings in downstream configurations.
unittests
=> remove vestiges of interpolation syntax that was deprecated in TF v0.12+

aws-acm-certificate/README.md, aws-acm-certificate/main.tf, aws-acm-certificate/module_test.go, aws-acm-certificate/outputs.tf, aws-acm-certificate/terraform.tf, aws-acm-certificate/variables.tf
Adds a new aws-acm-certificate module, intended to replace aws-acm-cert for Terraform AWS Provider >=3.0.
Users of TF AWS Provider <3.0 must continue using aws-acm-cert module, which is now officially deprecated; it should be deleted once all uses of it are done.
Although cloudposse provides their own module https://github.com/cloudposse/terraform-aws-acm-request-certificate it does not have some features that we use, such as verifying subject alternative names on different Route 53 zones than the one used for the main domain, so we will for now continue maintaining our own.
The following changes are made:
* Removal of hacks cert_subject_alternative_names_count and cert_subject_alternative_names_order
* Replacing individual project/env/service/owner inputs with a single tags input that …
=> [feature] aws-acm-certificate module compatible with TF AWS Provider >3.0

aws-aurora-mysql/main.tf, aws-aurora-mysql/variables.tf, aws-aurora-postgres/main.tf, aws-aurora-postgres/variables.tf, aws-aurora/main.tf, aws-aurora/variables.tf
This will support creating a new RDS cluster from an existing snapshot, e.g. for data mirroring to a different env.
If snapshot_identifier not provided, should revert to original behavior.
This takes functionality from a side branch of @atolopko-czi  and puts it into the main branch, since there is already code that relies on this functionality.
=> [feature] Add 'snapshot_identifier' to all aws-aurora modules

aws-acm-certificate/README.md, aws-aurora-mysql/README.md, aws-aurora-postgres/README.md, aws-aurora/README.md, aws-ecs-service-fargate/README.md, aws-ecs-service-fargate/alb.tf, aws-ecs-service-fargate/outputs.tf, aws-ecs-service-fargate/service.tf, aws-ecs-service/README.md, aws-ecs-service/alb.tf, aws-ecs-service/outputs.tf, aws-ecs-service/service.tf, aws-lambda-function/main.tf, aws-redis-node/README.md, aws-redis-node/main.tf, aws-redis-replication-group/README.md, aws-redis-replication-group/main.tf, aws-single-page-static-site/main.tf, aws-single-page-static-site/providers.tf, aws-ssm-params/README.md, github-webhooks-to-s3/README.md
* Shorten static site lambda name
* Remove unneeded bare aws provider from static site
* Fix aws-ssm-params readme
* Upgrade terraform-aws-modules/security-group/aws for TF 3.0 compatiblity (and update since new version renames output this_security_group_id to security_group_id)
* aws-lambda-functionaws_cloudwatch_log_group use ARN instead of manually
constructing since ARN is fixed in TF AWS 3.0
* Update readmes via make docs
=> [fix] Various fixes for TF AWS 3.0 compatibility

aws-params-reader-policy/main.tf
When trying to use the `ssm:DescribeParameters` permission, I keep getting this warning: 
```
The actions in your policy do not support resource-level permissions and require you to choose All resources
```
The warning is right--I wasn't able to run `ssm:DescribeParameters` for a specific subpath in SSM.
=> [fix] remove ssm:DescribeParameters permission from SSM reader policy

aws-aurora-mysql/README.md, aws-aurora-postgres/README.md, aws-cloudfront-domain-redirect/README.md, aws-cloudfront-logs-bucket/README.md, aws-cloudwatch-log-retention-manager/README.md, aws-iam-role-admin/README.md, aws-iam-role-bless/README.md, aws-iam-role-ci-user-manager/README.md, aws-iam-role-cloudfront-poweruser/README.md, aws-iam-role-crossacct/README.md, aws-iam-role-ec2-poweruser/README.md, aws-iam-role-ecs-poweruser/README.md, aws-iam-role-infraci/README.md, aws-iam-role-poweruser/README.md, aws-iam-role-readonly/README.md, aws-iam-role-route53domains-poweruser/README.md, aws-iam-role-security-audit/README.md, aws-iam-role/README.md, aws-iam-role/main.tf, aws-iam-role/variables.tf, aws-lambda-edge-add-security-headers/README.md, aws-single-page-static-site/README.md, aws-sns-lambda/README.md, bless-ca/README.md, github-webhooks-to-s3/README.md
aws-iam-role: Allow specifying the SAML:aud condition on SAML IDPs. We typically want this in situations where we can do credentials passthrough.
There are also a bunch of stalre READMEs that got updated
=> feat(aws-iam-role): Allow configuring SAML IDPs and SAML:aud

.github/workflows/release-please.yml
This PR adds the release-please Github action to the repo. The release-please action will take care of all releases by creating a release PR that can be merged whenever a release is ready to be made.
- It finds the commit messages to main and adds them to the changelog automatically
- It versions the repo based on the types of conventional commits
- It automatically publishes a release when the release PR is merged
- It is run by the prodsec github user whose credentials can be found in 1password in the prodsec vault
* [Release-please](https://github.com/googleapis/release-please)
=> chore: adding release-please to cztack

.github/workflows/release-please.yml
This PR adds a version pin to the release-please action because I have noticed a bug in the main branch a few times. As a way to make sure we don't have flaky changelog, pinning a known working version should make that more stable.
=> fix: release-please version pin

.github/dependabot.yml
Mergebot prevents dependabot from rebasing PRs. Don't tag with mergebot label
=> fix: dependabot no mergebot label

aws-ecs-service-fargate/README.md, aws-ecs-service-fargate/alb.tf, aws-ecs-service-fargate/variables.tf
Support a slow start parameter for Fargate services to bring their configuration to parity with EC2 services
=> support slow start for fargate.

aws-lambda-edge-add-security-headers/main.tf
Upgraded node version to `node14.x` as support for `node10.x` has been deprecated.
=> Upgraded node version

aws-aurora-postgres/main.tf, aws-aurora-postgres/module_test.go, aws-aurora-postgres/variables.tf
Adding deletion_protection as a variable. Before, this defaulted to false because the `aws-aurora` module defaulted this variable to false.
=> feat: Variablize deletion_protection for aurora-postgres module

.github/workflows/release-please.yml
This PR removes the hard coded dependency on the prodsec secret and uses the CZI github action as the token for creating releases.
=> fix: release-please version and token

.github/workflows/mods.yml
This PR removes the dependency on the buildbot token. I don't think it is needed anymore and by default will use the GITHUB_TOKEN.
=> fix: remove dep on buildbot token

aws-aurora-mysql/README.md, aws-aurora-mysql/main.tf, aws-aurora-mysql/module_test.go, aws-aurora-mysql/variables.tf, aws-aurora-postgres/README.md, aws-aurora-postgres/main.tf, aws-aurora-postgres/variables.tf, aws-aurora/README.md, aws-aurora/main.tf, aws-aurora/module_test.go, aws-aurora/variables.tf
`params_engine_version` was being calculated for naming purposes and wasn't being used as an actual input. Removing and reconfiguring the `aws-aurora` module.
=> feat: Update `aws-aurora` module to not use `params_engine_version`

aws-ecs-job-fargate/README.md, aws-ecs-job-fargate/iam.tf, aws-ecs-job-fargate/variables.tf
Adding an option to attach ssm permission to ecs fargate job module. This option can be used when the task running in ECS Fargate needs to use parameter store to retrieve secret credentials.
Background on why we needed this: We plan to deploy a docker image on ECS Fargate which needs to set some authentication credentials as its environment variables. Since these are confidential credentials, we have stored them in parameter store and hence ECS task needs access to that store to retrieve them.
=> feat: Attach ssm permissions to ecs fargate job module

aws-ecs-service-fargate/main.tf
Update to this module to disallow names longer than 32 characters. Here is an example:
~~~
> format("%.32s", "blahhhhhhh-blahhhhhh-blahhhhzzzzzzzzzzzzzzzzzzz")
"blahhhhhhh-blahhhhhh-blahhhhzzzz"
~~~
=> feat: limit the number of character to the maximum 32 chars

aws-assume-role-policy/main.tf, aws-assume-role-policy/module_test.go, aws-assume-role-policy/variables.tf, aws-iam-role-crossacct/main.tf, aws-iam-role-crossacct/module_test.go, aws-iam-role-crossacct/variables.tf
Allows for cross account roles to add a role arn to the trust policy and not just a root account.
Testing through usage in shared_infra for adding a role arn to the trust policy
https://czi-tech.atlassian.net/browse/CCIE-679
=> feat: add source role arns

aws-cloudfront-domain-redirect/README.md, aws-cloudfront-domain-redirect/main.tf, aws-cloudfront-domain-redirect/variables.tf, aws-lambda-edge-add-security-headers/README.md, aws-lambda-edge-add-security-headers/main.tf, aws-lambda-edge-add-security-headers/variables.tf
Make this parameter configurable for a consuming TF project. Otherwise it defaults to `null`, which is the equivalent of 0. A 0 day retention policy makes those logs essentially useless.
I think somebody previously made a change in the UI to configure a 30 day retention policy on these logs. Hence, a plan (without this PR) was prompting TF to change the retention policy from 30 to 0 days. 
I tested this PR out by running `make plan` on the consuming TF project and noting that the 30 to 0 day change is no longer prompted.
=> feat: configure log retention in aws-lambda-edge-add-security-headers module

aws-ecr-repo/.terraform.lock.hcl, aws-ecr-repo/README.md, aws-ecr-repo/main.tf, aws-ecr-repo/module_test.go, aws-ecr-repo/outputs.tf, aws-ecr-repo/variables.tf, aws-ecr-repo/versions.tf
This PR adds a module for ECR repositories. The module creates an ECR repository with tags and configured name and optionally allows for a few configuration options such as force_delete (for terraform destroys), access policies, and lifecycle policies.
=> feat: add module for ecr repository

aws-iam-role-github-action/README.md, aws-iam-role-github-action/main.tf, aws-iam-role-github-action/outputs.tf, aws-iam-role-github-action/variables.tf, aws-iam-role-github-action/versions.tf, scripts/snowflake_generate_grant_all/ensure_ci.go, scripts/snowflake_generate_grant_all/main.go
A role that can be used by Github Actions to assume into based on what repo is trusted.
=> feat: make github CI role opensource

aws-aurora-postgres/outputs.tf, aws-aurora/outputs.tf
Propagate additional outputs to aws-aurora-postgres module.
- cluster_resource_id is useful for if you want to enable iam authentication on the database. The IAM policy requires a reference to the resource id. https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html
- the cluster_id is useful for providing unique names for other resources that are tied to the aurora instance
=> feat: output additional info from aws-aurora-postgres

aws-s3-private-bucket/main.tf
AWS provider 5.x removed the deprecated attribute source_json.
=> fix: Replace a deprecated source_json attribute

aws-s3-private-bucket/variables.tf
`null` cannot be the second argument of `contains()`. Use the ternary operator to check for null first, and then if not, check using `contains()` (with the 2nd argument guaranteed to be non-null).
```
> null == null ? true : contains(["a", "b", "c"], null)
true
```
=> fix: Ternary operator for variable validation check against null

aws-s3-private-bucket/main.tf
Supply the `id` of the bucket and not the `aws_s3_bucket` resource itself to the `aws_s3_bucket_ownership_controls` resource.
=> fix: Use id and not resource itself as value

aws-s3-private-bucket/main.tf, aws-s3-private-bucket/outputs.tf, aws-s3-private-bucket/variables.tf, aws-s3-private-bucket/versions.tf
Add functionality to set private s3 bucket encryption to use a specified (new) KMS key instead of the default SSE-S3 keys,  allowing cross-account access to the bucket without needing to assume a role in the target AWS account
=> feat: CDI-1607 Add KMS encryption key var to s3 bucket

aws-s3-private-bucket/main.tf
This PR removes a deprecated attribute on s3 buckets and moves out into the resource aws_s3_bucket_server_side_encryption_configuration
=> chore: remove deprecated attribute

aws-params-writer/main.tf
Removing `overwrite` as it will be deprecated argument in `v6.0.0` of the provider.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_parameter
=> feat: Remove deprecated overwrite parameter

aws-s3-private-bucket/variables.tf
Previous change set s3 KMS encryption by default
=> fix: Do not set S3 kms encryption by default

aws-s3-private-bucket/README.md
Prior [PR](https://github.com/chanzuckerberg/cztack/pull/516) did not trigger release-please
Also, update docs
=> fix: trigger release for S3 default KMS encryption fix

aws-iam-role-github-action/main.tf, aws-iam-role-github-action/variables.tf
This PR allows the Github Role to have more than just IdP references. We can easily make the role trusted by another AWS account or through a generic trust relation JSON policy.
=> feat: all more options when creating the trust relationship

databricks-metastore/README.md, databricks-metastore/main.tf, databricks-metastore/outputs.tf, databricks-metastore/provider.tf, databricks-metastore/s3.tf, databricks-metastore/variables.tf, databricks-metastore/versions.tf
Copy `databricks-metastore` from shared-infra to cztack
- [project plan](https://docs.google.com/document/d/18CbAB2z_ypiLwOIkIEY1xdwfzlIVAXo55M58_PxhayU/edit)
=> feat: CDI-2180 - Add databricks-metastore module

databricks-workspace-e2/README.md, databricks-workspace-e2/aws_iam_role.tf, databricks-workspace-e2/bucket.tf, databricks-workspace-e2/main.tf, databricks-workspace-e2/outputs.tf, databricks-workspace-e2/security_group.tf, databricks-workspace-e2/variables.tf, databricks-workspace-e2/versions.tf
Copy `databricks-workspace-e2` from shared-infra to cztack
=> feat: CDI-2179 - Add databricks-workspace-e2 module

databricks-cluster-log-permissions/README.md, databricks-cluster-log-permissions/main.tf, databricks-cluster-log-permissions/outputs.tf, databricks-cluster-log-permissions/providers.tf, databricks-cluster-log-permissions/variables.tf, databricks-cluster-log-permissions/versions.tf
Copy `databricks-cluster-log-permissions` from shared-infra to cztack
=> feat: CDI-2183 Add databricks-cluster-log-permissions module

databricks-cluster-policy/README.md, databricks-cluster-policy/main.tf, databricks-cluster-policy/variables.tf, databricks-cluster-policy/versions.tf
Copy `databricks-cluster-policy` from shared-infra to cztack
=> feat: CDI-2181 Add databricks-cluster-policy module

databricks-cluster-policy/README.md, databricks-cluster-policy/main.tf, databricks-cluster-policy/variables.tf, databricks-cluster-policy/versions.tf, databricks-default-cluster-policies/README.md, databricks-default-cluster-policies/main.tf, databricks-default-cluster-policies/variables.tf, databricks-default-cluster-policies/versions.tf
Copy `databricks-default-cluster-policies` from shared-infra to cztack
- leverages https://github.com/chanzuckerberg/cztack/pull/530
=> feat: CDI-2182 Add databricks-default-cluster-policy module

databricks-workspace-e2/variables.tf
Variable was copied over from shared-infra, but isn't actually used (though there was a default value) - dropping
=> fix: CDI-2179 Remove unused databricks-workspace-e2 variable

databricks-default-cluster-policies/main.tf
Override prevents multi-node job clusters from running, as it expects a variable to be present that isn't added unless the cluster is of single-node type
=> fix: Split out job compute policy between single and multi node

databricks-default-cluster-policies/main.tf
Adds `i3-xlarge-pool` pool usage permissions to Personal Compute cluster policies
=> feat: add pool use to personal compute Databricks policy

databricks-default-cluster-policies/main.tf, databricks-default-cluster-policies/variables.tf
Rather than hard-coding, this requires a by-workspace variable as the pool ID is workspace dependent.
=> fix: personal instance pools var for databricks compute policies

aws-aurora-postgres/outputs.tf
This PR adds the sensitive attribute to the outputs of this module which are required by newer versions of terraform. Specifically, master_password is a sensitive attribute and needs to marked as such otherwise terraform will throw:
~~~
╷
│ Error: Output refers to sensitive values
│ 
│   on outputs.tf line 24:
│   24: output "master_password" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true
╵
~~~
=> fix: mark outputs with sensitive attribute

databricks-default-cluster-policies/main.tf
This PR gives account-level policy groups in Databricks permissions to use the associated workspaces where the policies are enacted.
Will apply using ie databricks to make sure the permissions are properly loaded, then will upgrade all remaining databricks policy modules.
=> chore: [ONCALL-693] Add account-level groups to default Databricks policies

databricks-default-cluster-policies/main.tf
This PR adds a small comment to the default Databricks policies to remind developers to first create a user group in the account for permissions assignments.
It also serves to trigger deployment of this module to include changes made in #550.
=> fix: [ONCALL-693] Trigger release of databricks-default-cluster-policies

databricks-cluster-policy/main.tf
TF provider requires all grants on the same resource to be in the same resource block, requiring use of a dynamic block instead of a standard for_each
=> fix: CDI-2604 Databricks cluster policy permission grants not being applied correctly

aws-s3-private-bucket/main.tf
There were two encryption configs that were overriding each other in the applies. There should only be one chosen based on the `kms_encryption` variable.
=> fix: Choose one type of encryption for buckets

databricks-default-cluster-policies/main.tf
Allow the use of on-demand instances for the Job Compute policy.
Spot instances are already too flaky for ETL work. The problem is worse with GPU workloads.
GPU workloads have the additional problem of low availability and longer provisioning times.
Additional on-demand instances will be scaled down so the additional cost is only temporary when using auto-scaling.
=> feat: Allow on demand instances for databricks job compute policy

databricks-default-cluster-policies/main.tf
Update small single node dbx cluster policy to work with jobs - does not support autotermination
Test deploy on a cluster with these changes manually added
=> fix: CDI_2906 - Update custom job policy to work with jobs

databricks-default-cluster-policies/main.tf
Current setup doesn't create any workers but also doesn't specify that there shouldn't be any, causing the driver to fail to schedule jobs against non-existent workers
Tested manually on ie-databricks
=> fix: CDI-2906 Fix attributes for single node job compute

aws-assume-role-policy/main.tf, aws-assume-role-policy/variables.tf, aws-assume-role-policy/versions.tf, aws-iam-role-crossacct/variables.tf, aws-iam-role-crossacct/versions.tf
=> feat: add jwt_condition option to oidc variable for IAM trust relationships

aws-assume-role-policy/main.tf, aws-assume-role-policy/variables.tf, aws-iam-role-crossacct/variables.tf
https://czi-tech.atlassian.net/browse/CCIE-3183
=> feat: add condition_operator field to allow overriding StringEquals with StringLike

databricks-catalog-external-location/main.tf
=> fix: CDI-3183 - Allow dbx storage credentials roles to be self-assuming

aws-aurora-mysql/main.tf, aws-aurora-mysql/variables.tf, aws-aurora-postgres/main.tf, aws-aurora-postgres/variables.tf, aws-aurora/main.tf, aws-aurora/variables.tf
Adds iam_role argument to the `aws-aurora` modules
unittests
The VC litqa agent embddings db requires the ability to add iam_roles to the db cluster
=> chore: add iam_role argument to aws-aurora, aws-aurora-postgres, aws-aurora-mysql

databricks-catalog-external-location/catalogs.tf, databricks-catalog-external-location/variables.tf
I want to be able to give a hardcoded prefix name in case we wanted to not have to recreate a storage bucket for a catalog when renaming the catalog.
=> feat: Catalog prefix option

databricks-catalog-external-location/catalogs.tf, databricks-s3-volume/grants.tf
`BROWSE` is needed for all users to be able to see the catalogs in the Catalog Explorer. 
https://docs.databricks.com/en/data-governance/unity-catalog/manage-privileges/privileges.html#browse
=> feat: Add BROWSE to catalog perms

databricks-catalog-external-location/catalogs.tf
catalog is dependent on external location to be created
=> fix: Add depends_on to databricks_catalog

databricks-s3-volume/grants.tf
Catalog permissions don't work right now - they include superfluous permissions like `CREATE_CONNECTION`. This PR downscopes all permissions to relatively minimal permissions, and adds only ones that are directly applicable to the object type (rather than pushing lower level object permissions to upper level entities)
https://docs.databricks.com/en/data-governance/unity-catalog/manage-privileges/privileges.html
=> fix: CDI-3446 Refine and downscope UC grants for volume

databricks-s3-volume/grants.tf
Despite documentation on Databricks site, `READ_FILES` and `WRITE_FILES` don't seem to be supported permissions for volumes. Removing them here
=> fix: CDI-3446 - Remove read_file permissions from dbx volume

databricks-s3-volume/bucket.tf, databricks-s3-volume/main.tf, databricks-s3-volume/outputs.tf, databricks-s3-volume/variables.tf
- Fix references for dbx volumes to allow creating volume on existing catalog and bucket
- Add support for additional/override bucket policies for buckets created using module
- Add support for bucket name specification
- Rename catalog_owner var to owner, since its applied everywhere
=> fix: CDI-3452 - Fix references for dbx volumes to allow creating volume on existing catalog and bucket

databricks-default-cluster-policies/main.tf, databricks-default-cluster-policies/variables.tf
This group was causing issues if you wanted to create multiple versions of this module in one env.
=> fix: Move out power user group

.github/workflows/ci.yml, .golangci.yml, aws-s3-public-bucket/module_test.go, bless-ca/test/module_test.go
This change is for updating linter in this repo. James' [PR](https://github.com/chanzuckerberg/cztack/actions/runs/11490041738/job/32020193024) has been failing on this issue, so we're upgrading the go lint package to the latest and to used our self-hosted runner.
As long as all check pass, it should be fine.
[Argus Lint yaml](https://github.com/chanzuckerberg/argus/blob/12e26b94100f5ce86d3f92ee7d5a886abd1c97a5/.github/workflows/core-ci.yaml)
=> feat: update go lint

databricks-catalog-external-location/main.tf
Fix the role managing access to a Databricks external location to be self-assuming.
- TFE checks
- ran in a development environment
https://docs.databricks.com/en/connect/unity-catalog/storage-credentials.html#step-3-update-the-iam-role-trust-relationship-policy
=> fix: databricks-catalog-external-location - Make role self-assuming

databricks-catalog-external-location/main.tf
It was invalid to have a role policy document to refer to the same role for it. This succeeded if the role had existing previously; this was failing for new rows Instead, creating a separate `aws_iam_role_policy` to ensure the role is created first, and then the attachment follows.
- TFE plan
- Validated in remote-dev environment
=> fix: Ensure Databricks external location role exists before making it self-referential

aws-iam-role-s3-readonly/README.md, aws-iam-role-s3-readonly/main.tf, aws-iam-role-s3-readonly/module_test.go, aws-iam-role-s3-readonly/outputs.tf, aws-iam-role-s3-readonly/variables.tf
This module is created for granting Biohub folks to have only readonly access to particular s3 buckets
Module passing
=> feat: biohub s3 readonly role

aws-iam-role-s3-readonly/main.tf, aws-iam-role-s3-readonly/variables.tf
A follow up for this [pr](https://github.com/chanzuckerberg/cztack/pull/669)
=> fix: add oidc input to assume role policy

aws-iam-role-s3-readonly/README.md, aws-iam-role-s3-readonly/main.tf
=> fix: update s3 bucket name typo

databricks-s3-volume/grants.tf, databricks-s3-volume/variables.tf
=> fix: remove non-applicable permission from dbx volume grant and add all privileges group

databricks-s3-volume/grants.tf
Previous PR re-defined an attribute, which is not allowed by downstream linters given that its bad practice
=> fix: set dbx volume var once

databricks-s3-volume-existing-catalog/grants.tf, databricks-s3-volume/main.tf
Fixing attribute name for read-write principals to match that of read principals, also making consistent with usage below of the `volume_name` attribute.
=> fix: variable name

databricks-s3-volume/iam.tf, databricks-s3-volume/main.tf, databricks-s3-volume/variables.tf
Breaks out storage credential creation between catalogs and volumes, allowing situations where we want to create a multiple volumes on an existing catalog
=> fix: CDI-3949 fix dbx volume storage credentials

databricks-s3-volume-existing-catalog/grants.tf
Iterating over grants using the volume name was eliminating grant pairs with the same volume name. Using index to make entries unique.
Tested in TFE workspace
[CDI-3890]
[CDI-3890]: https://czi.atlassian.net/browse/CDI-3890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Use index as key instead of volume name for grants iterator for Databricks Volume creation

databricks-default-cluster-policies/groups.tf, databricks-default-cluster-policies/outputs.tf
Previously, as a list of usergroups was associated per cluster policy, only the first usergroup in the usergroup list was being added to the cluster policy's group membership.
Instead, "flattening" out to a list of policy-to-group mappings, and creating `databricks_group_member`ship for each explicitly. Each `databricks_group_member` resource is now named after the pairing instead of just the policy name.
Tested in local TF workspace.
=> fix: Assign all listed Databricks usergroups to associated Databricks cluster policy groups
